theme: minima
title: Div's Blog
author: DivInsAll
description: This is where I am going to document my coding journey. This will be where I write my successes, failures, and other experiences. 

# social links
github_username:  DivInsAll

show_excerpts: true # set to false to remove excerpts on the homepage
